repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: hugo-validate
        name: Hugo validate
        entry: hugo --minify --environment production --destination public
        language: system
        pass_filenames: false
