# The URL the site will be built for
base_url = "https://gabelluardo.github.io"

title = "Gabelluardo"
default_language = "en"

theme = "terminimal"
compile_sass = true

generate_feed = true
feed_filename = "rss.xml"
minify_html = true

# NOTE: for blog posts
# taxonomies = [
#   { name = "tags" },
# ]

# [languages.it]
# generate_feed = true
# taxonomies = [
#   { name = "tags" },
# ]


[markdown]
highlight_code = true
highlight_theme = "nyx-bold"

[extra]
menu_items = [
  # each of these is optional, name and url are required
  # $BASE_URL is going to be substituted by base_url from configuration
  { name = "home", url = "$BASE_URL" },

  # tags should only be enabled if you have "tags" taxonomy
  # see documentation below for more details
  #{ name = "blog", url = "$BASE_URL/blog" },
  #{ name = "tags", url = "$BASE_URL/tags" },
  #{ name = "archive", url = "$BASE_URL/archive" },
  { name = "github", url = "https://github.com/gabelluardo", newtab = true },
  { name = "twitter", url = "https://twitter.com/ugabbel", newtab = true }
]

# One of: blue, green, orange, pink, red.
# Defaults to blue.
accent_color = "green"

# One of: blue, dark, green, orange, pink, red.
# Enabling dark background will also modify primary font color
# to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
# background_color = "green"

logo_text = "Gabelluardo"

# The logo link - defaults to base_url.
# logo_home_link = "/take/me/away!"

# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
author = "Gabriele Belluardo"
footer_copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

# Whether to show links to earlier and later posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Other posts"

# Use full Hack character set, not just a subset.
# Switch this to true if you need full unicode support.
# Defaults to false.
use_full_hack_font = false

# Optional: Global favicon URL and mimetype.
#           Mimetype defaults to "image/x-icon".
#           The URL should point at a file located
#           in your site's "static" directory.
favicon = "/favicon-32x32.png"
favicon_mimetype = "image/png"


[extra.matomo]
enable = false
url = "gbsrv.duckdns.org/matomo"
id = 4

[extra.goatcounter]
enable = true
code = "gabelluardo"

[extra.google_analytics]
enable = false
id = "UA-169315751-2"

