name: LHCI Analisys

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lighthouseci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Build site
        run: deno task build

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: "./lighthouserc.yml"
          temporaryPublicStorage: true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
